version: '3.3'

services:
  mymessenger_frontend:
    container_name: 'mymessenger_frontend'
    build: ./ClientApp
    ports:
      - "4201:4200"
    depends_on:
      - mymessenger_backend
    volumes:
      - ./ClientApp:/usr/src/ClientApp
      - /usr/src/ClientApp/node_modules

  mymessenger_backend:
    container_name: 'mymessenger_backend'
    image: 'mymessenger_backend'
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    build:
      context: .
      dockerfile: MyMessenger.WebApi/Dockerfile
    ports:
     - "8000:80"
    depends_on:
     - mymessenger_db
    networks:
      - mymessenger_dev

  mymessenger_db:
    image: 'postgres:12.2'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345678"
      POSTGRES_DB: "MyMessenger"
    restart: always
    volumes:
       - db_volume:/var/lib/postgresql/data
    networks:
      - mymessenger_dev

volumes:
  db_volume:

networks:
  mymessenger_dev:
    driver: bridge